services:
  redis:
    image: redis:8.0-M02-bookworm
    container_name: redis-container
    ports:
      - "6379:6379"
    restart: always

  mysql:
    image: mysql:8.0.40-debian
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: project_management
      MYSQL_ROOT_PASSWORD: ${DATASOURCE_PASSWORD}
      MYSQL_USER: user
      MYSQL_PASSWORD: user@123
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - ${DOCKER_VOLUME_FILE}

volumes:
  ${DOCKER_VOLUME}:
    external: true

