spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/project_manager"
    username: "root"
    password: "Nuocbangh2o#"

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

api:
  prefix: "/project_management/v1"

file:
  upload-dir: "D:\\Documents\\IdeaProjects\\Project_Management\\Folder_Storage\\"

