spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3307/project_management"
    username: "root"
    password: "Nuocbangh2o#"


  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

api:
  prefix: "/project_management/v1"

file:
  upload-dir: "D:\\Documents\\Folder_Storage\\"

secret:
  key: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"




